### ISSUE TITLE
link to React-lego as an example?

### ISSUE THREAD

**Issue by peter-mouland** [zen-js-code/react-universal-web-apps#7]
Hi,  I have implemented the concepts you talk about in the blog post and implemented them in an example project.  Would you be kind enough to link to [React-lego](https://github.com/peter-mouland/react-lego)?

As a quick intro, I started the project to help people implement ideas and new techs one piece at a time.  I found many starter-apps or boiler-plates etc were often all singing / all dancing and could be hard to disect.

The section/branch which implements the promise-middle ware is https://github.com/peter-mouland/react-lego#redux-with-promise-middleware

**Comment by dnutels** [comment]
Hi.

Unfortunately, I don't control the editing process of Smashing magazine, so, I suggest to post that into comments of the article.
